-- seed_exercise_catalog.sql
-- Run this in the Supabase SQL editor or a migration with database-owner
-- privileges. The frontend should not have write access to exercise_catalog.
-- ON CONFLICT (db_id) DO NOTHING means safe to re-run.

INSERT INTO public.exercise_catalog (db_id, name, muscles, secondary, equipment, pattern, category)
VALUES
  -- CHEST
  ('e-bench-press','Barbell Bench Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'barbell','push','barbell'),
  ('e-incline-bench','Incline Barbell Bench Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'barbell','push','barbell'),
  ('e-decline-bench','Decline Barbell Bench Press',ARRAY['chest'],ARRAY['triceps'],'barbell','push','barbell'),
  ('e-close-grip-bench','Close Grip Bench Press',ARRAY['triceps'],ARRAY['chest','shoulders'],'barbell','push','barbell'),
  ('e-db-bench','Dumbbell Bench Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'dumbbell','push','dumbbell'),
  ('e-db-incline','Incline Dumbbell Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'dumbbell','push','dumbbell'),
  ('e-db-decline','Decline Dumbbell Press',ARRAY['chest'],ARRAY['triceps'],'dumbbell','push','dumbbell'),
  ('e-db-fly','Dumbbell Fly',ARRAY['chest'],ARRAY['shoulders'],'dumbbell','push','dumbbell'),
  ('e-incline-fly','Incline Dumbbell Fly',ARRAY['chest'],ARRAY['shoulders'],'dumbbell','push','dumbbell'),
  ('e-cable-fly','Cable Fly (High to Low)',ARRAY['chest'],ARRAY['shoulders'],'cable','push','cable'),
  ('e-cable-fly-low','Cable Fly (Low to High)',ARRAY['chest'],ARRAY['shoulders'],'cable','push','cable'),
  ('e-cable-crossover','Cable Crossover',ARRAY['chest'],ARRAY['shoulders'],'cable','push','cable'),
  ('e-pec-deck','Pec Deck / Machine Fly',ARRAY['chest'],ARRAY[]::text[],'machine','push','machine'),
  ('e-chest-press-machine','Chest Press Machine',ARRAY['chest'],ARRAY['shoulders','triceps'],'machine','push','machine'),
  ('e-smith-bench','Smith Machine Bench Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'machine','push','machine'),
  ('e-pushup','Push-Up',ARRAY['chest'],ARRAY['shoulders','triceps'],'bodyweight','push','bodyweight'),
  ('e-wide-pushup','Wide Grip Push-Up',ARRAY['chest'],ARRAY['shoulders','triceps'],'bodyweight','push','bodyweight'),
  ('e-diamond-pushup','Diamond Push-Up',ARRAY['triceps'],ARRAY['chest'],'bodyweight','push','bodyweight'),
  ('e-archer-pushup','Archer Push-Up',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),
  ('e-dips-chest','Chest Dips',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),

  -- BACK — LATS
  ('e-pullup','Pull-Up',ARRAY['lats'],ARRAY['biceps','traps'],'bodyweight','pull','calisthenics'),
  ('e-chinup','Chin-Up',ARRAY['lats'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-assisted-pullup','Assisted Pull-Up',ARRAY['lats'],ARRAY['biceps'],'machine','pull','machine'),
  ('e-lat-pulldown','Lat Pulldown',ARRAY['lats'],ARRAY['biceps','traps'],'cable','pull','cable'),
  ('e-lat-pulldown-wide','Wide Grip Lat Pulldown',ARRAY['lats'],ARRAY['biceps'],'cable','pull','cable'),
  ('e-lat-pulldown-close','Close Grip Lat Pulldown',ARRAY['lats'],ARRAY['biceps'],'cable','pull','cable'),
  ('e-lat-pulldown-reverse','Reverse Grip Lat Pulldown',ARRAY['lats'],ARRAY['biceps'],'cable','pull','cable'),
  ('e-straight-arm-pulldown','Straight Arm Pulldown',ARRAY['lats'],ARRAY['core'],'cable','pull','cable'),
  ('e-single-arm-pulldown','Single Arm Lat Pulldown',ARRAY['lats'],ARRAY['biceps'],'cable','pull','cable'),
  ('e-db-pullover','Dumbbell Pullover',ARRAY['lats'],ARRAY['chest','traps'],'dumbbell','pull','dumbbell'),
  ('e-bb-pullover','Barbell Pullover',ARRAY['lats'],ARRAY['chest'],'barbell','pull','barbell'),

  -- BACK — ROWS
  ('e-bb-row','Barbell Bent-Over Row',ARRAY['back'],ARRAY['lats','biceps','traps'],'barbell','pull','barbell'),
  ('e-bb-row-overhand','Barbell Row (Overhand)',ARRAY['back'],ARRAY['lats','traps','biceps'],'barbell','pull','barbell'),
  ('e-bb-row-underhand','Barbell Row (Underhand)',ARRAY['back'],ARRAY['biceps','lats'],'barbell','pull','barbell'),
  ('e-pendlay-row','Pendlay Row',ARRAY['back'],ARRAY['lats','traps'],'barbell','pull','barbell'),
  ('e-tbar-row','T-Bar Row',ARRAY['back'],ARRAY['lats','biceps'],'barbell','pull','barbell'),
  ('e-db-row','Dumbbell Bent-Over Row',ARRAY['back'],ARRAY['lats','biceps'],'dumbbell','pull','dumbbell'),
  ('e-db-row-single','Single Arm Dumbbell Row',ARRAY['back'],ARRAY['lats','biceps'],'dumbbell','pull','dumbbell'),
  ('e-seated-cable-row','Seated Cable Row',ARRAY['back'],ARRAY['lats','biceps'],'cable','pull','cable'),
  ('e-seated-row-wide','Seated Cable Row (Wide Grip)',ARRAY['back'],ARRAY['lats'],'cable','pull','cable'),
  ('e-cable-row-single','Single Arm Cable Row',ARRAY['back'],ARRAY['lats','biceps'],'cable','pull','cable'),
  ('e-machine-row','Machine Row',ARRAY['back'],ARRAY['lats','biceps'],'machine','pull','machine'),
  ('e-chest-supported-row','Chest Supported Row',ARRAY['back'],ARRAY['lats'],'machine','pull','machine'),
  ('e-inverted-row','Inverted Row',ARRAY['back'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-face-pull','Face Pull',ARRAY['traps'],ARRAY['shoulders','back'],'cable','pull','cable'),

  -- BACK — TRAPS / UPPER BACK
  ('e-shrug-bb','Barbell Shrug',ARRAY['traps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-shrug-db','Dumbbell Shrug',ARRAY['traps'],ARRAY[]::text[],'dumbbell','pull','dumbbell'),
  ('e-shrug-cable','Cable Shrug',ARRAY['traps'],ARRAY[]::text[],'cable','pull','cable'),
  ('e-shrug-machine','Machine Shrug',ARRAY['traps'],ARRAY[]::text[],'machine','pull','machine'),
  ('e-upright-row-bb','Barbell Upright Row',ARRAY['traps'],ARRAY['shoulders'],'barbell','pull','barbell'),
  ('e-upright-row-db','Dumbbell Upright Row',ARRAY['traps'],ARRAY['shoulders'],'dumbbell','pull','dumbbell'),
  ('e-deadrow','Meadows Row',ARRAY['back'],ARRAY['lats','biceps'],'barbell','pull','barbell'),

  -- SHOULDERS
  ('e-ohp','Overhead Press (Barbell)',ARRAY['shoulders'],ARRAY['triceps','traps'],'barbell','push','barbell'),
  ('e-push-press','Push Press',ARRAY['shoulders'],ARRAY['triceps','quads'],'barbell','push','barbell'),
  ('e-db-ohp','Dumbbell Overhead Press',ARRAY['shoulders'],ARRAY['triceps'],'dumbbell','push','dumbbell'),
  ('e-arnold-press','Arnold Press',ARRAY['shoulders'],ARRAY['triceps'],'dumbbell','push','dumbbell'),
  ('e-seated-db-press','Seated Dumbbell Press',ARRAY['shoulders'],ARRAY['triceps'],'dumbbell','push','dumbbell'),
  ('e-machine-press-shoulder','Machine Shoulder Press',ARRAY['shoulders'],ARRAY['triceps'],'machine','push','machine'),
  ('e-smith-ohp','Smith Machine Overhead Press',ARRAY['shoulders'],ARRAY['triceps'],'machine','push','machine'),
  ('e-lateral-raise-db','Lateral Raise (Dumbbell)',ARRAY['shoulders'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-lateral-raise-cable','Lateral Raise (Cable)',ARRAY['shoulders'],ARRAY[]::text[],'cable','push','cable'),
  ('e-lateral-raise-machine','Lateral Raise (Machine)',ARRAY['shoulders'],ARRAY[]::text[],'machine','push','machine'),
  ('e-front-raise-db','Front Raise (Dumbbell)',ARRAY['shoulders'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-front-raise-bb','Front Raise (Barbell)',ARRAY['shoulders'],ARRAY[]::text[],'barbell','push','barbell'),
  ('e-front-raise-cable','Front Raise (Cable)',ARRAY['shoulders'],ARRAY[]::text[],'cable','push','cable'),
  ('e-rear-delt-fly-db','Rear Delt Fly (Dumbbell)',ARRAY['shoulders'],ARRAY['traps','back'],'dumbbell','pull','dumbbell'),
  ('e-rear-delt-fly-cable','Rear Delt Fly (Cable)',ARRAY['shoulders'],ARRAY['traps'],'cable','pull','cable'),
  ('e-rear-delt-machine','Rear Delt Machine',ARRAY['shoulders'],ARRAY['traps'],'machine','pull','machine'),
  ('e-pec-deck-reverse','Reverse Pec Deck',ARRAY['shoulders'],ARRAY['traps','back'],'machine','pull','machine'),
  ('e-pike-pushup','Pike Push-Up',ARRAY['shoulders'],ARRAY['triceps'],'bodyweight','push','calisthenics'),
  ('e-hspu','Handstand Push-Up',ARRAY['shoulders'],ARRAY['triceps','traps'],'bodyweight','push','calisthenics'),
  ('e-cuban-press','Cuban Press',ARRAY['shoulders'],ARRAY['traps'],'dumbbell','push','dumbbell'),

  -- BICEPS
  ('e-curl-bb','Barbell Curl',ARRAY['biceps'],ARRAY['forearms'],'barbell','pull','barbell'),
  ('e-curl-ez','EZ Bar Curl',ARRAY['biceps'],ARRAY['forearms'],'barbell','pull','barbell'),
  ('e-curl-db','Dumbbell Curl',ARRAY['biceps'],ARRAY['forearms'],'dumbbell','pull','dumbbell'),
  ('e-curl-db-alt','Alternating Dumbbell Curl',ARRAY['biceps'],ARRAY['forearms'],'dumbbell','pull','dumbbell'),
  ('e-hammer-curl','Hammer Curl',ARRAY['biceps'],ARRAY['forearms'],'dumbbell','pull','dumbbell'),
  ('e-incline-curl','Incline Dumbbell Curl',ARRAY['biceps'],ARRAY[]::text[],'dumbbell','pull','dumbbell'),
  ('e-concentration-curl','Concentration Curl',ARRAY['biceps'],ARRAY[]::text[],'dumbbell','pull','dumbbell'),
  ('e-preacher-curl-bb','Preacher Curl (Barbell)',ARRAY['biceps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-preacher-curl-db','Preacher Curl (Dumbbell)',ARRAY['biceps'],ARRAY[]::text[],'dumbbell','pull','dumbbell'),
  ('e-cable-curl','Cable Curl',ARRAY['biceps'],ARRAY['forearms'],'cable','pull','cable'),
  ('e-cable-curl-single','Single Arm Cable Curl',ARRAY['biceps'],ARRAY[]::text[],'cable','pull','cable'),
  ('e-machine-curl','Machine Curl',ARRAY['biceps'],ARRAY[]::text[],'machine','pull','machine'),
  ('e-reverse-curl','Reverse Curl',ARRAY['forearms'],ARRAY['biceps'],'barbell','pull','barbell'),
  ('e-spider-curl','Spider Curl',ARRAY['biceps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-cross-body-curl','Cross Body Hammer Curl',ARRAY['biceps'],ARRAY['forearms'],'dumbbell','pull','dumbbell'),
  ('e-zottman-curl','Zottman Curl',ARRAY['biceps'],ARRAY['forearms'],'dumbbell','pull','dumbbell'),

  -- TRICEPS
  ('e-skullcrusher','Skull Crusher (EZ Bar)',ARRAY['triceps'],ARRAY[]::text[],'barbell','push','barbell'),
  ('e-skullcrusher-db','Skull Crusher (Dumbbell)',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-tricep-pushdown','Tricep Pushdown (Bar)',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-tricep-pushdown-rope','Tricep Pushdown (Rope)',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-tricep-pushdown-single','Single Arm Tricep Pushdown',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-overhead-tricep-cable','Overhead Tricep Extension (Cable)',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-overhead-tricep-db','Overhead Tricep Extension (DB)',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-overhead-tricep-bb','Overhead Tricep Extension (BB)',ARRAY['triceps'],ARRAY[]::text[],'barbell','push','barbell'),
  ('e-dips-tricep','Tricep Dips',ARRAY['triceps'],ARRAY['chest','shoulders'],'bodyweight','push','calisthenics'),
  ('e-bench-dip','Bench Dip',ARRAY['triceps'],ARRAY['shoulders'],'bodyweight','push','bodyweight'),
  ('e-machine-tricep','Tricep Machine',ARRAY['triceps'],ARRAY[]::text[],'machine','push','machine'),
  ('e-kickback-db','Tricep Kickback (Dumbbell)',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-kickback-cable','Tricep Kickback (Cable)',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-jm-press','JM Press',ARRAY['triceps'],ARRAY['chest'],'barbell','push','barbell'),

  -- FOREARMS / WRISTS
  ('e-wrist-curl','Wrist Curl',ARRAY['forearms'],ARRAY[]::text[],'barbell','other','barbell'),
  ('e-wrist-curl-reverse','Reverse Wrist Curl',ARRAY['forearms'],ARRAY[]::text[],'barbell','other','barbell'),
  ('e-wrist-roller','Wrist Roller',ARRAY['forearms'],ARRAY[]::text[],'other','other','other'),
  ('e-plate-pinch','Plate Pinch',ARRAY['forearms'],ARRAY[]::text[],'other','carry','other'),
  ('e-farmers-carry','Farmer''s Carry',ARRAY['forearms'],ARRAY['traps','core','glutes'],'dumbbell','carry','dumbbell'),
  ('e-farmers-carry-bb','Farmer''s Carry (Barbell)',ARRAY['forearms'],ARRAY['traps','core'],'barbell','carry','barbell'),
  ('e-dead-hang','Dead Hang',ARRAY['forearms'],ARRAY['lats','shoulders'],'bodyweight','other','calisthenics'),

  -- LEGS — QUADS
  ('e-squat','Barbell Back Squat',ARRAY['quads'],ARRAY['glutes','hamstrings','core'],'barbell','squat','barbell'),
  ('e-front-squat','Barbell Front Squat',ARRAY['quads'],ARRAY['glutes','core'],'barbell','squat','barbell'),
  ('e-high-bar-squat','High Bar Squat',ARRAY['quads'],ARRAY['glutes'],'barbell','squat','barbell'),
  ('e-low-bar-squat','Low Bar Squat',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-paused-squat','Paused Squat',ARRAY['quads'],ARRAY['glutes'],'barbell','squat','barbell'),
  ('e-box-squat','Box Squat',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-goblet-squat','Goblet Squat',ARRAY['quads'],ARRAY['glutes','core'],'kettlebell','squat','kettlebell'),
  ('e-db-squat','Dumbbell Squat',ARRAY['quads'],ARRAY['glutes'],'dumbbell','squat','dumbbell'),
  ('e-hack-squat','Hack Squat Machine',ARRAY['quads'],ARRAY['glutes'],'machine','squat','machine'),
  ('e-leg-press','Leg Press',ARRAY['quads'],ARRAY['glutes','hamstrings'],'machine','squat','machine'),
  ('e-leg-press-wide','Leg Press (Wide Stance)',ARRAY['quads'],ARRAY['glutes','hamstrings'],'machine','squat','machine'),
  ('e-leg-ext','Leg Extension',ARRAY['quads'],ARRAY[]::text[],'machine','squat','machine'),
  ('e-sissy-squat','Sissy Squat',ARRAY['quads'],ARRAY[]::text[],'bodyweight','squat','bodyweight'),
  ('e-lunge-bb','Barbell Lunge',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-lunge-db','Dumbbell Lunge',ARRAY['quads'],ARRAY['glutes','hamstrings'],'dumbbell','squat','dumbbell'),
  ('e-lunge-walking','Walking Lunge',ARRAY['quads'],ARRAY['glutes'],'dumbbell','squat','dumbbell'),
  ('e-lunge-reverse','Reverse Lunge',ARRAY['quads'],ARRAY['glutes'],'bodyweight','squat','bodyweight'),
  ('e-split-squat','Bulgarian Split Squat',ARRAY['quads'],ARRAY['glutes'],'dumbbell','squat','dumbbell'),
  ('e-split-squat-bb','Bulgarian Split Squat (Barbell)',ARRAY['quads'],ARRAY['glutes'],'barbell','squat','barbell'),
  ('e-step-up','Step-Up',ARRAY['quads'],ARRAY['glutes'],'dumbbell','squat','dumbbell'),
  ('e-pistol-squat','Pistol Squat',ARRAY['quads'],ARRAY['glutes','core'],'bodyweight','squat','calisthenics'),
  ('e-smith-squat','Smith Machine Squat',ARRAY['quads'],ARRAY['glutes'],'machine','squat','machine'),
  ('e-sumo-squat-db','Sumo Squat (Dumbbell)',ARRAY['quads'],ARRAY['glutes','hamstrings'],'dumbbell','squat','dumbbell'),

  -- LEGS — HAMSTRINGS / GLUTES
  ('e-rdl','Romanian Deadlift (Barbell)',ARRAY['hamstrings'],ARRAY['glutes','back'],'barbell','hinge','barbell'),
  ('e-rdl-db','Romanian Deadlift (Dumbbell)',ARRAY['hamstrings'],ARRAY['glutes','back'],'dumbbell','hinge','dumbbell'),
  ('e-rdl-single','Single Leg RDL',ARRAY['hamstrings'],ARRAY['glutes'],'dumbbell','hinge','dumbbell'),
  ('e-leg-curl-lying','Lying Leg Curl',ARRAY['hamstrings'],ARRAY[]::text[],'machine','pull','machine'),
  ('e-leg-curl-seated','Seated Leg Curl',ARRAY['hamstrings'],ARRAY[]::text[],'machine','pull','machine'),
  ('e-leg-curl-standing','Standing Leg Curl',ARRAY['hamstrings'],ARRAY[]::text[],'machine','pull','machine'),
  ('e-nordic-curl','Nordic Hamstring Curl',ARRAY['hamstrings'],ARRAY[]::text[],'bodyweight','pull','calisthenics'),
  ('e-glute-bridge','Glute Bridge',ARRAY['glutes'],ARRAY['hamstrings'],'bodyweight','hinge','bodyweight'),
  ('e-hip-thrust-bb','Barbell Hip Thrust',ARRAY['glutes'],ARRAY['hamstrings'],'barbell','hinge','barbell'),
  ('e-hip-thrust-db','Dumbbell Hip Thrust',ARRAY['glutes'],ARRAY['hamstrings'],'dumbbell','hinge','dumbbell'),
  ('e-hip-thrust-machine','Hip Thrust Machine',ARRAY['glutes'],ARRAY['hamstrings'],'machine','hinge','machine'),
  ('e-cable-kickback','Cable Glute Kickback',ARRAY['glutes'],ARRAY['hamstrings'],'cable','hinge','cable'),
  ('e-donkey-kick','Donkey Kick',ARRAY['glutes'],ARRAY[]::text[],'bodyweight','hinge','bodyweight'),
  ('e-sumo-deadlift','Sumo Deadlift',ARRAY['glutes'],ARRAY['hamstrings','quads','back'],'barbell','hinge','barbell'),
  ('e-hip-abduction','Hip Abduction Machine',ARRAY['glutes'],ARRAY[]::text[],'machine','other','machine'),
  ('e-hip-adduction','Hip Adduction Machine',ARRAY['glutes'],ARRAY[]::text[],'machine','other','machine'),
  ('e-lateral-band-walk','Lateral Band Walk',ARRAY['glutes'],ARRAY[]::text[],'band','other','band'),
  ('e-fire-hydrant','Fire Hydrant',ARRAY['glutes'],ARRAY[]::text[],'bodyweight','other','bodyweight'),

  -- DEADLIFTS
  ('e-deadlift','Conventional Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings','traps'],'barbell','hinge','barbell'),
  ('e-trap-bar-deadlift','Trap Bar Deadlift',ARRAY['quads'],ARRAY['glutes','hamstrings','back'],'barbell','hinge','barbell'),
  ('e-deficit-deadlift','Deficit Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings'],'barbell','hinge','barbell'),
  ('e-rack-pull','Rack Pull',ARRAY['back'],ARRAY['traps','glutes'],'barbell','hinge','barbell'),
  ('e-stiff-leg-deadlift','Stiff Leg Deadlift',ARRAY['hamstrings'],ARRAY['glutes','back'],'barbell','hinge','barbell'),
  ('e-snatch-grip-deadlift','Snatch Grip Deadlift',ARRAY['back'],ARRAY['traps','glutes','hamstrings'],'barbell','hinge','barbell'),

  -- CALVES
  ('e-calf-raise-standing','Standing Calf Raise',ARRAY['calves'],ARRAY[]::text[],'machine','other','machine'),
  ('e-calf-raise-seated','Seated Calf Raise',ARRAY['calves'],ARRAY[]::text[],'machine','other','machine'),
  ('e-calf-raise-leg-press','Leg Press Calf Raise',ARRAY['calves'],ARRAY[]::text[],'machine','other','machine'),
  ('e-calf-raise-bb','Barbell Calf Raise',ARRAY['calves'],ARRAY[]::text[],'barbell','other','barbell'),
  ('e-calf-raise-db','Single Leg Calf Raise (DB)',ARRAY['calves'],ARRAY[]::text[],'dumbbell','other','dumbbell'),
  ('e-calf-raise-bw','Bodyweight Calf Raise',ARRAY['calves'],ARRAY[]::text[],'bodyweight','other','bodyweight'),
  ('e-jump-rope','Jump Rope',ARRAY['calves'],ARRAY['core','shoulders'],'other','cardio','cardio'),

  -- CORE
  ('e-crunch','Crunch',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-cable-crunch','Cable Crunch',ARRAY['core'],ARRAY[]::text[],'cable','core','cable'),
  ('e-sit-up','Sit-Up',ARRAY['core'],ARRAY['hip flexors'],'bodyweight','core','bodyweight'),
  ('e-decline-crunch','Decline Sit-Up',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-leg-raise','Hanging Leg Raise',ARRAY['core'],ARRAY['hip flexors'],'bodyweight','core','calisthenics'),
  ('e-knee-raise','Hanging Knee Raise',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','calisthenics'),
  ('e-leg-raise-lying','Lying Leg Raise',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-plank','Plank',ARRAY['core'],ARRAY['shoulders'],'bodyweight','core','bodyweight'),
  ('e-side-plank','Side Plank',ARRAY['core'],ARRAY['shoulders'],'bodyweight','core','bodyweight'),
  ('e-ab-wheel','Ab Wheel Rollout',ARRAY['core'],ARRAY['lats','shoulders'],'other','core','other'),
  ('e-dragon-flag','Dragon Flag',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','calisthenics'),
  ('e-l-sit','L-Sit',ARRAY['core'],ARRAY['triceps','shoulders'],'bodyweight','core','calisthenics'),
  ('e-oblique-crunch','Oblique Crunch',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-russian-twist','Russian Twist',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-wood-chop','Cable Wood Chop',ARRAY['core'],ARRAY['shoulders'],'cable','core','cable'),
  ('e-pallof-press','Pallof Press',ARRAY['core'],ARRAY[]::text[],'cable','core','cable'),
  ('e-toes-to-bar','Toes to Bar',ARRAY['core'],ARRAY['lats'],'bodyweight','core','calisthenics'),
  ('e-bicycle-crunch','Bicycle Crunch',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-hollow-hold','Hollow Body Hold',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','calisthenics'),
  ('e-flutter-kick','Flutter Kick',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-dead-bug','Dead Bug',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-v-up','V-Up',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-ghr','Glute Ham Raise',ARRAY['hamstrings'],ARRAY['glutes','core'],'machine','hinge','machine'),

  -- OLYMPIC LIFTS
  ('e-clean','Power Clean',ARRAY['back'],ARRAY['glutes','quads','traps','shoulders'],'barbell','hinge','olympic'),
  ('e-hang-clean','Hang Clean',ARRAY['back'],ARRAY['glutes','traps','shoulders'],'barbell','hinge','olympic'),
  ('e-snatch','Power Snatch',ARRAY['back'],ARRAY['glutes','shoulders','traps'],'barbell','hinge','olympic'),
  ('e-hang-snatch','Hang Snatch',ARRAY['back'],ARRAY['shoulders','glutes'],'barbell','hinge','olympic'),
  ('e-clean-jerk','Clean & Jerk',ARRAY['back'],ARRAY['glutes','quads','shoulders'],'barbell','hinge','olympic'),
  ('e-clean-pull','Clean Pull',ARRAY['back'],ARRAY['glutes','traps'],'barbell','hinge','olympic'),
  ('e-high-pull','High Pull',ARRAY['traps'],ARRAY['shoulders','back'],'barbell','pull','olympic'),
  ('e-muscle-snatch','Muscle Snatch',ARRAY['shoulders'],ARRAY['traps','back'],'barbell','push','olympic'),

  -- KETTLEBELL
  ('e-kb-swing','Kettlebell Swing',ARRAY['glutes'],ARRAY['hamstrings','back','core'],'kettlebell','hinge','kettlebell'),
  ('e-kb-swing-single','Single Arm Kettlebell Swing',ARRAY['glutes'],ARRAY['hamstrings','core'],'kettlebell','hinge','kettlebell'),
  ('e-kb-clean','Kettlebell Clean',ARRAY['back'],ARRAY['glutes','forearms'],'kettlebell','hinge','kettlebell'),
  ('e-kb-press','Kettlebell Press',ARRAY['shoulders'],ARRAY['triceps','core'],'kettlebell','push','kettlebell'),
  ('e-kb-snatch','Kettlebell Snatch',ARRAY['shoulders'],ARRAY['glutes','back'],'kettlebell','hinge','kettlebell'),
  ('e-kb-goblet-squat','Kettlebell Goblet Squat',ARRAY['quads'],ARRAY['glutes','core'],'kettlebell','squat','kettlebell'),
  ('e-kb-turkish-getup','Turkish Get-Up',ARRAY['core'],ARRAY['shoulders','glutes'],'kettlebell','other','kettlebell'),
  ('e-kb-rdl','Kettlebell RDL',ARRAY['hamstrings'],ARRAY['glutes'],'kettlebell','hinge','kettlebell'),
  ('e-kb-row','Kettlebell Row',ARRAY['back'],ARRAY['biceps','lats'],'kettlebell','pull','kettlebell'),
  ('e-kb-windmill','Kettlebell Windmill',ARRAY['core'],ARRAY['shoulders','hamstrings'],'kettlebell','core','kettlebell'),
  ('e-kb-figure8','Kettlebell Figure 8',ARRAY['core'],ARRAY['glutes'],'kettlebell','core','kettlebell'),

  -- CALISTHENICS / SKILL
  ('e-muscle-up','Muscle-Up',ARRAY['lats'],ARRAY['chest','triceps'],'bodyweight','pull','calisthenics'),
  ('e-front-lever','Front Lever',ARRAY['lats'],ARRAY['core','back'],'bodyweight','pull','calisthenics'),
  ('e-back-lever','Back Lever',ARRAY['lats'],ARRAY['chest','core'],'bodyweight','push','calisthenics'),
  ('e-planche','Planche',ARRAY['chest'],ARRAY['shoulders','core'],'bodyweight','push','calisthenics'),
  ('e-ring-dip','Ring Dip',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),
  ('e-ring-row','Ring Row',ARRAY['back'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-ring-pushup','Ring Push-Up',ARRAY['chest'],ARRAY['triceps','core'],'bodyweight','push','calisthenics'),
  ('e-typewriter-pullup','Typewriter Pull-Up',ARRAY['lats'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-commando-pullup','Commando Pull-Up',ARRAY['lats'],ARRAY['biceps','traps'],'bodyweight','pull','calisthenics'),
  ('e-human-flag','Human Flag',ARRAY['lats'],ARRAY['core','shoulders'],'bodyweight','other','calisthenics'),
  ('e-dip-bar-lrow','Dip Bar L-Sit Row',ARRAY['back'],ARRAY['core'],'bodyweight','pull','calisthenics'),

  -- CARDIO / CONDITIONING
  ('e-run','Running',ARRAY['quads'],ARRAY['hamstrings','calves','core'],'none','cardio','cardio'),
  ('e-sprint','Sprint',ARRAY['quads'],ARRAY['hamstrings','glutes','calves'],'none','cardio','cardio'),
  ('e-stair-climb','Stair Climber',ARRAY['quads'],ARRAY['glutes','calves'],'machine','cardio','cardio'),
  ('e-rowing-machine','Rowing Machine',ARRAY['back'],ARRAY['lats','core','legs'],'machine','cardio','cardio'),
  ('e-assault-bike','Assault Bike',ARRAY['quads'],ARRAY['shoulders','core'],'machine','cardio','cardio'),
  ('e-elliptical','Elliptical',ARRAY['quads'],ARRAY['hamstrings','glutes'],'machine','cardio','cardio'),
  ('e-cycling','Cycling',ARRAY['quads'],ARRAY['hamstrings','glutes','calves'],'machine','cardio','cardio'),
  ('e-swimming','Swimming',ARRAY['lats'],ARRAY['shoulders','core'],'none','cardio','cardio'),
  ('e-burpee','Burpee',ARRAY['core'],ARRAY['chest','shoulders','quads'],'bodyweight','cardio','bodyweight'),
  ('e-box-jump','Box Jump',ARRAY['quads'],ARRAY['glutes','calves'],'other','cardio','other'),
  ('e-broad-jump','Broad Jump',ARRAY['quads'],ARRAY['glutes','hamstrings'],'bodyweight','cardio','bodyweight'),
  ('e-mountain-climber','Mountain Climber',ARRAY['core'],ARRAY['shoulders','quads'],'bodyweight','cardio','bodyweight'),
  ('e-battle-ropes','Battle Ropes',ARRAY['shoulders'],ARRAY['core','back'],'other','cardio','other'),
  ('e-sled-push','Sled Push',ARRAY['quads'],ARRAY['glutes','shoulders'],'other','cardio','other'),
  ('e-sled-pull','Sled Pull',ARRAY['back'],ARRAY['glutes','hamstrings'],'other','cardio','other'),
  ('e-tire-flip','Tire Flip',ARRAY['back'],ARRAY['glutes','shoulders'],'other','cardio','other'),

  -- NECK
  ('e-neck-curl','Neck Curl',ARRAY['neck'],ARRAY[]::text[],'other','other','other'),
  ('e-neck-extension','Neck Extension',ARRAY['neck'],ARRAY[]::text[],'other','other','other'),
  ('e-neck-lateral','Neck Lateral Flexion',ARRAY['neck'],ARRAY[]::text[],'other','other','other'),
  ('e-neck-harness','Neck Harness',ARRAY['neck'],ARRAY['traps'],'other','other','other'),

  -- STRETCHES / MOBILITY
  ('e-hip-flexor-stretch','Hip Flexor Stretch',ARRAY['glutes'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-pigeon-pose','Pigeon Pose',ARRAY['glutes'],ARRAY['hamstrings'],'bodyweight','stretch','stretch'),
  ('e-hamstring-stretch','Hamstring Stretch',ARRAY['hamstrings'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-quad-stretch','Quad Stretch',ARRAY['quads'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-calf-stretch','Calf Stretch',ARRAY['calves'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-chest-stretch','Chest Stretch',ARRAY['chest'],ARRAY['shoulders'],'bodyweight','stretch','stretch'),
  ('e-lats-stretch','Lat Stretch',ARRAY['lats'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-shoulder-stretch','Cross-Body Shoulder Stretch',ARRAY['shoulders'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-thoracic-rotation','Thoracic Rotation',ARRAY['back'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-spinal-twist','Spinal Twist Stretch',ARRAY['back'],ARRAY['core'],'bodyweight','stretch','stretch'),
  ('e-childs-pose','Child''s Pose',ARRAY['back'],ARRAY['lats','shoulders'],'bodyweight','stretch','stretch'),
  ('e-cobra-stretch','Cobra Stretch',ARRAY['core'],ARRAY['back'],'bodyweight','stretch','stretch'),
  ('e-world-greatest','World''s Greatest Stretch',ARRAY['glutes'],ARRAY['hamstrings','core','shoulders'],'bodyweight','stretch','stretch'),
  ('e-ankle-mobility','Ankle Circles / Mobility',ARRAY['calves'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-foam-roll-quads','Foam Roll — Quads',ARRAY['quads'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-foam-roll-it-band','Foam Roll — IT Band',ARRAY['quads'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-foam-roll-back','Foam Roll — Upper Back',ARRAY['back'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-band-pull-apart','Band Pull Apart',ARRAY['traps'],ARRAY['shoulders','back'],'band','pull','band'),
  ('e-face-pull-band','Band Face Pull',ARRAY['traps'],ARRAY['shoulders'],'band','pull','band'),

  -- CHEST additional
  ('e-svend-press','Svend Press',ARRAY['chest'],ARRAY[]::text[],'other','push','other'),
  ('e-low-cable-fly','Low Cable Fly',ARRAY['chest'],ARRAY['shoulders'],'cable','push','cable'),
  ('e-incline-cable-fly','Incline Cable Fly',ARRAY['chest'],ARRAY['shoulders'],'cable','push','cable'),
  ('e-single-arm-chest-press','Single Arm DB Chest Press',ARRAY['chest'],ARRAY['triceps','core'],'dumbbell','push','dumbbell'),
  ('e-loaded-stretch-fly','Loaded Stretch Fly',ARRAY['chest'],ARRAY['shoulders'],'dumbbell','push','dumbbell'),
  ('e-hs-chest-press','Hammer Strength Chest Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'machine','push','machine'),
  ('e-incline-hs-press','Hammer Strength Incline Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'machine','push','machine'),
  ('e-cable-chest-press','Standing Cable Chest Press',ARRAY['chest'],ARRAY['triceps','core'],'cable','push','cable'),
  ('e-smith-incline','Smith Machine Incline Press',ARRAY['chest'],ARRAY['shoulders','triceps'],'machine','push','machine'),
  ('e-db-pullover-chest','DB Pullover (Chest Focus)',ARRAY['chest'],ARRAY['lats'],'dumbbell','push','dumbbell'),
  ('e-banded-pushup','Banded Push-Up',ARRAY['chest'],ARRAY['triceps','shoulders'],'band','push','band'),
  ('e-decline-pushup','Decline Push-Up',ARRAY['chest'],ARRAY['shoulders','triceps'],'bodyweight','push','bodyweight'),
  ('e-plyometric-pushup','Plyometric Push-Up',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),

  -- BACK additional
  ('e-db-pullover-back','DB Pullover (Back Focus)',ARRAY['lats'],ARRAY['chest'],'dumbbell','pull','dumbbell'),
  ('e-meadows-row','Meadows Row',ARRAY['back'],ARRAY['lats','biceps'],'barbell','pull','barbell'),
  ('e-yates-row','Yates Row',ARRAY['back'],ARRAY['biceps','lats'],'barbell','pull','barbell'),
  ('e-chest-supported-db-row','Chest Supported DB Row',ARRAY['back'],ARRAY['lats','biceps'],'dumbbell','pull','dumbbell'),
  ('e-seated-cable-row-wide','Wide Grip Seated Cable Row',ARRAY['back'],ARRAY['lats'],'cable','pull','cable'),
  ('e-cable-row-low','Low Cable Row',ARRAY['back'],ARRAY['lats','biceps'],'cable','pull','cable'),
  ('e-neutral-grip-pulldown','Neutral Grip Lat Pulldown',ARRAY['lats'],ARRAY['biceps'],'cable','pull','cable'),
  ('e-hs-row','Hammer Strength Row',ARRAY['back'],ARRAY['lats','biceps'],'machine','pull','machine'),
  ('e-hs-pulldown','Hammer Strength Pulldown',ARRAY['lats'],ARRAY['biceps'],'machine','pull','machine'),
  ('e-iso-row','Iso-Lateral Row',ARRAY['back'],ARRAY['lats','biceps'],'machine','pull','machine'),
  ('e-cable-pullover','Cable Pullover',ARRAY['lats'],ARRAY['chest','core'],'cable','pull','cable'),
  ('e-band-row','Band Row',ARRAY['back'],ARRAY['biceps'],'band','pull','band'),
  ('e-ring-muscle-up','Ring Muscle-Up',ARRAY['lats'],ARRAY['chest','triceps'],'bodyweight','pull','calisthenics'),
  ('e-straight-bar-pushdown','Straight Bar Lat Pushdown',ARRAY['lats'],ARRAY['core'],'cable','pull','cable'),
  ('e-wide-grip-row','Wide Grip Cable Row',ARRAY['back'],ARRAY['lats'],'cable','pull','cable'),

  -- SHOULDERS additional
  ('e-z-press','Z Press',ARRAY['shoulders'],ARRAY['triceps','core'],'barbell','push','barbell'),
  ('e-bradford-press','Bradford Press',ARRAY['shoulders'],ARRAY['triceps','traps'],'barbell','push','barbell'),
  ('e-db-lat-raise-seated','Seated Lateral Raise',ARRAY['shoulders'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-cable-lat-raise','Cable Lateral Raise',ARRAY['shoulders'],ARRAY[]::text[],'cable','push','cable'),
  ('e-band-lat-raise','Band Lateral Raise',ARRAY['shoulders'],ARRAY[]::text[],'band','push','band'),
  ('e-machine-lat-raise','Machine Lateral Raise',ARRAY['shoulders'],ARRAY[]::text[],'machine','push','machine'),
  ('e-cable-front-raise','Cable Front Raise',ARRAY['shoulders'],ARRAY[]::text[],'cable','push','cable'),
  ('e-plate-front-raise','Plate Front Raise',ARRAY['shoulders'],ARRAY[]::text[],'other','push','other'),
  ('e-db-rear-delt','Dumbbell Rear Delt Fly',ARRAY['shoulders'],ARRAY['traps'],'dumbbell','pull','dumbbell'),
  ('e-cable-rear-delt','Cable Rear Delt Fly',ARRAY['shoulders'],ARRAY['traps'],'cable','pull','cable'),
  ('e-machine-rear-delt','Machine Rear Delt Fly',ARRAY['shoulders'],ARRAY['traps'],'machine','pull','machine'),
  ('e-incline-lat-raise','Incline Lateral Raise',ARRAY['shoulders'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-landmine-press','Landmine Press',ARRAY['shoulders'],ARRAY['chest','triceps'],'barbell','push','barbell'),
  ('e-single-arm-press','Single Arm DB Overhead Press',ARRAY['shoulders'],ARRAY['triceps','core'],'dumbbell','push','dumbbell'),
  ('e-hs-shoulder-press','Hammer Strength Shoulder Press',ARRAY['shoulders'],ARRAY['triceps'],'machine','push','machine'),

  -- BICEPS additional
  ('e-reverse-curl-db','Reverse Dumbbell Curl',ARRAY['forearms'],ARRAY['biceps'],'dumbbell','pull','dumbbell'),
  ('e-drag-curl','Drag Curl',ARRAY['biceps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-cable-curl-rope','Cable Curl (Rope)',ARRAY['biceps'],ARRAY['forearms'],'cable','pull','cable'),
  ('e-incline-db-curl','Incline DB Curl',ARRAY['biceps'],ARRAY[]::text[],'dumbbell','pull','dumbbell'),
  ('e-crossbody-curl','Cross-Body Hammer Curl',ARRAY['biceps'],ARRAY['forearms'],'dumbbell','pull','dumbbell'),
  ('e-bayesian-curl','Bayesian Curl (Cable)',ARRAY['biceps'],ARRAY[]::text[],'cable','pull','cable'),
  ('e-overhead-cable-curl','Overhead Cable Curl',ARRAY['biceps'],ARRAY[]::text[],'cable','pull','cable'),
  ('e-band-curl','Band Curl',ARRAY['biceps'],ARRAY[]::text[],'band','pull','band'),
  ('e-chin-up-curl','Chin-Up (Curl Focus)',ARRAY['biceps'],ARRAY['lats'],'bodyweight','pull','calisthenics'),
  ('e-ez-curl','EZ Bar Curl',ARRAY['biceps'],ARRAY['forearms'],'barbell','pull','barbell'),

  -- TRICEPS additional
  ('e-tate-press','Tate Press',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-lying-tri-ext-ez','EZ Bar Lying Triceps Extension',ARRAY['triceps'],ARRAY[]::text[],'barbell','push','barbell'),
  ('e-db-tri-kickback','Dumbbell Triceps Kickback',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-overhead-db-ext','Overhead Dumbbell Extension',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),
  ('e-overhead-cable-ext','Overhead Cable Extension',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-rope-pushdown','Rope Pushdown',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-reverse-pushdown','Reverse Grip Pushdown',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-single-arm-pushdown','Single Arm Pushdown',ARRAY['triceps'],ARRAY[]::text[],'cable','push','cable'),
  ('e-tri-machine','Triceps Machine',ARRAY['triceps'],ARRAY[]::text[],'machine','push','machine'),
  ('e-band-pushdown','Band Pushdown',ARRAY['triceps'],ARRAY[]::text[],'band','push','band'),
  ('e-floor-tri-ext','Floor Triceps Extension',ARRAY['triceps'],ARRAY[]::text[],'dumbbell','push','dumbbell'),

  -- FOREARMS / GRIP additional
  ('e-wrist-curl-bb','Barbell Wrist Curl',ARRAY['forearms'],ARRAY[]::text[],'barbell','other','barbell'),
  ('e-wrist-curl-db','Dumbbell Wrist Curl',ARRAY['forearms'],ARRAY[]::text[],'dumbbell','other','dumbbell'),
  ('e-reverse-wrist-curl','Reverse Wrist Curl',ARRAY['forearms'],ARRAY[]::text[],'barbell','other','barbell'),
  ('e-farmers-walk','Farmer''s Walk',ARRAY['forearms'],ARRAY['traps','core','quads'],'dumbbell','carry','dumbbell'),
  ('e-pinch-grip','Pinch Grip Hold',ARRAY['forearms'],ARRAY[]::text[],'other','other','other'),
  ('e-gripper','Hand Gripper',ARRAY['forearms'],ARRAY[]::text[],'other','other','other'),
  ('e-rice-bucket','Rice Bucket Training',ARRAY['forearms'],ARRAY[]::text[],'other','other','other'),
  ('e-towel-pullup','Towel Pull-Up',ARRAY['forearms'],ARRAY['lats','biceps'],'bodyweight','pull','calisthenics'),

  -- QUADS additional
  ('e-hack-squat-bb','Barbell Hack Squat',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-pendulum-squat','Pendulum Squat',ARRAY['quads'],ARRAY['glutes'],'machine','squat','machine'),
  ('e-wall-sit','Wall Sit',ARRAY['quads'],ARRAY['glutes'],'bodyweight','squat','bodyweight'),
  ('e-step-up-bb','Barbell Step-Up',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-cable-squat','Cable Squat',ARRAY['quads'],ARRAY['glutes','core'],'cable','squat','cable'),
  ('e-tempo-squat','Tempo Squat',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-zercher-squat','Zercher Squat',ARRAY['quads'],ARRAY['glutes','core','back'],'barbell','squat','barbell'),
  ('e-belt-squat','Belt Squat',ARRAY['quads'],ARRAY['glutes'],'machine','squat','machine'),
  ('e-single-leg-press','Single Leg Press',ARRAY['quads'],ARRAY['glutes','hamstrings'],'machine','squat','machine'),
  ('e-reverse-lunge','Reverse Lunge',ARRAY['quads'],ARRAY['glutes','hamstrings'],'bodyweight','squat','bodyweight'),
  ('e-walking-lunge-bb','Barbell Walking Lunge',ARRAY['quads'],ARRAY['glutes','hamstrings'],'barbell','squat','barbell'),
  ('e-curtsy-lunge','Curtsy Lunge',ARRAY['quads'],ARRAY['glutes'],'dumbbell','squat','dumbbell'),

  -- HAMSTRINGS additional
  ('e-lying-leg-curl-single','Single Leg Lying Curl',ARRAY['hamstrings'],ARRAY['glutes'],'machine','hinge','machine'),
  ('e-cable-leg-curl','Cable Leg Curl',ARRAY['hamstrings'],ARRAY[]::text[],'cable','hinge','cable'),
  ('e-snatch-grip-rdl','Snatch Grip RDL',ARRAY['hamstrings'],ARRAY['back','traps'],'barbell','hinge','barbell'),
  ('e-single-leg-rdl-db','Single Leg RDL (DB)',ARRAY['hamstrings'],ARRAY['glutes','core'],'dumbbell','hinge','dumbbell'),
  ('e-single-leg-rdl-bb','Single Leg RDL (BB)',ARRAY['hamstrings'],ARRAY['glutes','core'],'barbell','hinge','barbell'),
  ('e-bb-good-morning','Barbell Good Morning',ARRAY['hamstrings'],ARRAY['back','glutes'],'barbell','hinge','barbell'),
  ('e-seated-good-morning','Seated Good Morning',ARRAY['hamstrings'],ARRAY['back'],'barbell','hinge','barbell'),
  ('e-ball-leg-curl','Swiss Ball Leg Curl',ARRAY['hamstrings'],ARRAY['glutes','core'],'other','hinge','other'),
  ('e-band-leg-curl','Band Leg Curl',ARRAY['hamstrings'],ARRAY[]::text[],'band','hinge','band'),
  ('e-inverse-leg-curl','Inverse Leg Curl',ARRAY['hamstrings'],ARRAY[]::text[],'machine','hinge','machine'),

  -- GLUTES additional
  ('e-hip-thrust-smith','Smith Machine Hip Thrust',ARRAY['glutes'],ARRAY['hamstrings'],'machine','hinge','machine'),
  ('e-hip-thrust-single','Single Leg Hip Thrust',ARRAY['glutes'],ARRAY['hamstrings','core'],'bodyweight','hinge','bodyweight'),
  ('e-cable-pull-through','Cable Pull-Through',ARRAY['glutes'],ARRAY['hamstrings'],'cable','hinge','cable'),
  ('e-glute-bridge-weighted','Weighted Glute Bridge',ARRAY['glutes'],ARRAY['hamstrings'],'barbell','hinge','barbell'),
  ('e-frog-pump','Frog Pump',ARRAY['glutes'],ARRAY[]::text[],'bodyweight','hinge','bodyweight'),
  ('e-band-hip-abduction','Band Hip Abduction',ARRAY['glutes'],ARRAY[]::text[],'band','other','band'),
  ('e-machine-abduction','Hip Abduction Machine',ARRAY['glutes'],ARRAY[]::text[],'machine','other','machine'),
  ('e-machine-adduction','Hip Adduction Machine',ARRAY['quads'],ARRAY['glutes'],'machine','other','machine'),
  ('e-clamshell','Clamshell',ARRAY['glutes'],ARRAY[]::text[],'band','other','band'),
  ('e-sumo-rdl','Sumo RDL',ARRAY['glutes'],ARRAY['hamstrings','quads'],'barbell','hinge','barbell'),

  -- CALVES additional
  ('e-seated-calf-raise','Seated Calf Raise',ARRAY['calves'],ARRAY[]::text[],'machine','push','machine'),
  ('e-single-calf-raise','Single Leg Calf Raise',ARRAY['calves'],ARRAY[]::text[],'bodyweight','push','bodyweight'),
  ('e-leg-press-calf','Leg Press Calf Raise',ARRAY['calves'],ARRAY[]::text[],'machine','push','machine'),
  ('e-tibialis-raise','Tibialis Raise',ARRAY['calves'],ARRAY[]::text[],'bodyweight','other','bodyweight'),

  -- TRAPS / UPPER BACK additional
  ('e-trap-bar-shrug','Trap Bar Shrug',ARRAY['traps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-behind-back-shrug','Behind-The-Back Shrug',ARRAY['traps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-db-upright-row','Dumbbell Upright Row',ARRAY['traps'],ARRAY['shoulders'],'dumbbell','pull','dumbbell'),
  ('e-cable-upright-row','Cable Upright Row',ARRAY['traps'],ARRAY['shoulders'],'cable','pull','cable'),
  ('e-snatch-grip-shrug','Snatch Grip Shrug',ARRAY['traps'],ARRAY[]::text[],'barbell','pull','barbell'),
  ('e-kb-shrug','Kettlebell Shrug',ARRAY['traps'],ARRAY[]::text[],'kettlebell','pull','kettlebell'),
  ('e-y-raise','Y Raise',ARRAY['traps'],ARRAY['shoulders','back'],'dumbbell','pull','dumbbell'),
  ('e-w-raise','W Raise',ARRAY['traps'],ARRAY['shoulders'],'dumbbell','pull','dumbbell'),
  ('e-seal-row','Seal Row',ARRAY['back'],ARRAY['lats','biceps'],'barbell','pull','barbell'),

  -- CORE additional
  ('e-weighted-crunch','Weighted Crunch',ARRAY['core'],ARRAY[]::text[],'other','core','other'),
  ('e-reverse-crunch','Reverse Crunch',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),
  ('e-plank-row','Plank Row',ARRAY['core'],ARRAY['back','biceps'],'dumbbell','core','dumbbell'),
  ('e-plank-reach','Plank Reach',ARRAY['core'],ARRAY['shoulders'],'bodyweight','core','bodyweight'),
  ('e-side-plank-reach','Side Plank with Reach',ARRAY['core'],ARRAY['shoulders'],'bodyweight','core','bodyweight'),
  ('e-weighted-sit-up','Weighted Sit-Up',ARRAY['core'],ARRAY[]::text[],'other','core','other'),
  ('e-garhammer-raise','Garhammer Raise',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','calisthenics'),
  ('e-suitcase-carry','Suitcase Carry',ARRAY['core'],ARRAY['traps','forearms'],'dumbbell','carry','dumbbell'),
  ('e-overhead-carry','Overhead Carry',ARRAY['core'],ARRAY['shoulders','traps'],'dumbbell','carry','dumbbell'),
  ('e-stir-the-pot','Stir the Pot (Ball Plank)',ARRAY['core'],ARRAY['shoulders'],'other','core','other'),
  ('e-landmine-rotation','Landmine Rotation',ARRAY['core'],ARRAY['shoulders','back'],'barbell','core','barbell'),
  ('e-band-pallof','Band Pallof Press',ARRAY['core'],ARRAY[]::text[],'band','core','band'),
  ('e-med-ball-slam','Medicine Ball Slam',ARRAY['core'],ARRAY['shoulders','back'],'other','core','other'),
  ('e-med-ball-throw','Medicine Ball Rotational Throw',ARRAY['core'],ARRAY['shoulders'],'other','core','other'),
  ('e-windshield-wiper','Windshield Wiper',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','calisthenics'),
  ('e-seated-knee-raise','Seated Knee Raise',ARRAY['core'],ARRAY['quads'],'bodyweight','core','bodyweight'),
  ('e-toe-touch-crunch','Toe Touch Crunch',ARRAY['core'],ARRAY[]::text[],'bodyweight','core','bodyweight'),

  -- DEADLIFT VARIATIONS (distinct IDs)
  ('e-stiff-leg-dl','Stiff Leg Deadlift',ARRAY['hamstrings'],ARRAY['back','glutes'],'barbell','hinge','barbell'),
  ('e-deficit-dl','Deficit Deadlift',ARRAY['hamstrings'],ARRAY['back','glutes','quads'],'barbell','hinge','barbell'),
  ('e-paused-dl','Paused Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings','traps'],'barbell','hinge','barbell'),
  ('e-snatch-grip-dl','Snatch Grip Deadlift',ARRAY['back'],ARRAY['traps','glutes','hamstrings'],'barbell','hinge','barbell'),
  ('e-sumo-dl','Sumo Deadlift',ARRAY['glutes'],ARRAY['hamstrings','quads','back'],'barbell','hinge','barbell'),
  ('e-dumbbell-dl','Dumbbell Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings'],'dumbbell','hinge','dumbbell'),
  ('e-trap-bar-dl','Trap Bar Deadlift',ARRAY['quads'],ARRAY['glutes','hamstrings','back'],'barbell','hinge','barbell'),
  ('e-smith-dl','Smith Machine Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings'],'machine','hinge','machine'),

  -- BENCH PRESS VARIATIONS
  ('e-paused-bench','Paused Bench Press',ARRAY['chest'],ARRAY['triceps','shoulders'],'barbell','push','barbell'),
  ('e-spoto-press','Spoto Press',ARRAY['chest'],ARRAY['triceps','shoulders'],'barbell','push','barbell'),
  ('e-board-press','Board Press',ARRAY['triceps'],ARRAY['chest','shoulders'],'barbell','push','barbell'),
  ('e-pin-press','Pin Press',ARRAY['chest'],ARRAY['triceps','shoulders'],'barbell','push','barbell'),
  ('e-floor-press','Floor Press',ARRAY['triceps'],ARRAY['chest'],'barbell','push','barbell'),
  ('e-floor-press-db','Dumbbell Floor Press',ARRAY['triceps'],ARRAY['chest'],'dumbbell','push','dumbbell'),
  ('e-slingshot-bench','Slingshot Bench Press',ARRAY['chest'],ARRAY['triceps','shoulders'],'barbell','push','barbell'),

  -- POWERLIFTING / STRONGMAN
  ('e-log-press','Log Press',ARRAY['shoulders'],ARRAY['triceps','core'],'other','push','other'),
  ('e-axle-dl','Axle Bar Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings','forearms'],'barbell','hinge','barbell'),
  ('e-yoke-walk','Yoke Walk',ARRAY['quads'],ARRAY['traps','core','glutes'],'other','carry','other'),
  ('e-atlas-stone','Atlas Stone Lift',ARRAY['back'],ARRAY['glutes','core','biceps'],'other','hinge','other'),
  ('e-keg-carry','Keg Carry',ARRAY['core'],ARRAY['shoulders','back'],'other','carry','other'),
  ('e-sandbag-carry','Sandbag Carry',ARRAY['core'],ARRAY['back','shoulders'],'other','carry','other'),
  ('e-loaded-carries','Loaded Carries (General)',ARRAY['core'],ARRAY['traps','forearms','quads'],'other','carry','other'),

  -- KETTLEBELL additional
  ('e-kb-deadlift','Kettlebell Deadlift',ARRAY['back'],ARRAY['glutes','hamstrings'],'kettlebell','hinge','kettlebell'),
  ('e-kb-sumo-dl','Kettlebell Sumo Deadlift',ARRAY['glutes'],ARRAY['hamstrings','quads'],'kettlebell','hinge','kettlebell'),
  ('e-kb-lunge','Kettlebell Lunge',ARRAY['quads'],ARRAY['glutes','hamstrings'],'kettlebell','squat','kettlebell'),
  ('e-kb-push-press','Kettlebell Push Press',ARRAY['shoulders'],ARRAY['triceps','quads'],'kettlebell','push','kettlebell'),
  ('e-kb-jerk','Kettlebell Jerk',ARRAY['shoulders'],ARRAY['triceps','quads','core'],'kettlebell','push','kettlebell'),
  ('e-kb-front-rack-squat','Kettlebell Front Rack Squat',ARRAY['quads'],ARRAY['core','glutes'],'kettlebell','squat','kettlebell'),
  ('e-kb-suitcase-dl','Kettlebell Suitcase Deadlift',ARRAY['back'],ARRAY['core','glutes'],'kettlebell','hinge','kettlebell'),
  ('e-kb-bottoms-up-press','Kettlebell Bottoms-Up Press',ARRAY['shoulders'],ARRAY['triceps','forearms'],'kettlebell','push','kettlebell'),
  ('e-kb-halo','Kettlebell Halo',ARRAY['shoulders'],ARRAY['core','traps'],'kettlebell','other','kettlebell'),
  ('e-kb-lateral-lunge','Kettlebell Lateral Lunge',ARRAY['quads'],ARRAY['glutes','hamstrings'],'kettlebell','squat','kettlebell'),
  ('e-kb-staggered-rdl','Kettlebell Staggered Stance RDL',ARRAY['hamstrings'],ARRAY['glutes'],'kettlebell','hinge','kettlebell'),

  -- CALISTHENICS additional
  ('e-wide-pullup','Wide Grip Pull-Up',ARRAY['lats'],ARRAY['biceps','back'],'bodyweight','pull','calisthenics'),
  ('e-narrow-pullup','Narrow Grip Pull-Up',ARRAY['lats'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-neutral-pullup','Neutral Grip Pull-Up',ARRAY['lats'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-band-assisted-pullup','Band Assisted Pull-Up',ARRAY['lats'],ARRAY['biceps'],'band','pull','band'),
  ('e-negative-pullup','Negative Pull-Up',ARRAY['lats'],ARRAY['biceps','traps'],'bodyweight','pull','calisthenics'),
  ('e-archer-pullup','Archer Pull-Up',ARRAY['lats'],ARRAY['biceps'],'bodyweight','pull','calisthenics'),
  ('e-pseudo-planche-pushup','Pseudo Planche Push-Up',ARRAY['chest'],ARRAY['shoulders','core'],'bodyweight','push','calisthenics'),
  ('e-handstand-pushup','Handstand Push-Up',ARRAY['shoulders'],ARRAY['triceps','traps'],'bodyweight','push','calisthenics'),
  ('e-wall-handstand-pushup','Wall Handstand Push-Up',ARRAY['shoulders'],ARRAY['triceps'],'bodyweight','push','calisthenics'),
  ('e-single-arm-pushup','Single Arm Push-Up',ARRAY['chest'],ARRAY['triceps','core'],'bodyweight','push','calisthenics'),
  ('e-clap-pushup','Clap Push-Up',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),
  ('e-bar-dip','Parallel Bar Dip',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),
  ('e-weighted-dip','Weighted Dip',ARRAY['chest'],ARRAY['triceps','shoulders'],'bodyweight','push','calisthenics'),
  ('e-weighted-pullup','Weighted Pull-Up',ARRAY['lats'],ARRAY['biceps','traps'],'bodyweight','pull','calisthenics'),
  ('e-bw-squat','Bodyweight Squat',ARRAY['quads'],ARRAY['glutes','hamstrings'],'bodyweight','squat','bodyweight'),
  ('e-jump-squat','Jump Squat',ARRAY['quads'],ARRAY['glutes','calves'],'bodyweight','squat','bodyweight'),
  ('e-squat-hold','Squat Hold (Deep)',ARRAY['quads'],ARRAY['glutes','hamstrings'],'bodyweight','squat','bodyweight'),

  -- CARDIO additional
  ('e-treadmill','Treadmill (Incline Walk)',ARRAY['quads'],ARRAY['hamstrings','calves','glutes'],'machine','cardio','cardio'),
  ('e-stationary-bike','Stationary Bike',ARRAY['quads'],ARRAY['hamstrings','calves'],'machine','cardio','cardio'),
  ('e-spin-bike','Spin Bike',ARRAY['quads'],ARRAY['hamstrings','calves','glutes'],'machine','cardio','cardio'),
  ('e-hiit','HIIT Circuit',ARRAY['core'],ARRAY['quads','shoulders'],'none','cardio','cardio'),
  ('e-tabata','Tabata',ARRAY['core'],ARRAY['quads','shoulders'],'none','cardio','cardio'),
  ('e-emom','EMOM',ARRAY['core'],ARRAY[]::text[],'none','cardio','cardio'),
  ('e-amrap','AMRAP',ARRAY['core'],ARRAY[]::text[],'none','cardio','cardio'),
  ('e-sledgehammer','Sledgehammer Swing',ARRAY['core'],ARRAY['shoulders','back'],'other','core','other'),
  ('e-rope-climb','Rope Climb',ARRAY['lats'],ARRAY['biceps','forearms'],'bodyweight','pull','calisthenics'),
  ('e-ski-erg','Ski Erg',ARRAY['lats'],ARRAY['core','shoulders'],'machine','cardio','cardio'),
  ('e-versa-climber','VersaClimber',ARRAY['shoulders'],ARRAY['lats','quads','core'],'machine','cardio','cardio'),
  ('e-stair-run','Stair Running',ARRAY['quads'],ARRAY['glutes','calves'],'none','cardio','cardio'),
  ('e-agility-ladder','Agility Ladder Drills',ARRAY['calves'],ARRAY['quads','core'],'other','cardio','cardio'),

  -- MOBILITY / WARMUP additional
  ('e-leg-swing','Leg Swing',ARRAY['glutes'],ARRAY['hamstrings'],'bodyweight','stretch','stretch'),
  ('e-arm-circle','Arm Circle',ARRAY['shoulders'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-inchworm','Inchworm',ARRAY['hamstrings'],ARRAY['core','shoulders'],'bodyweight','stretch','stretch'),
  ('e-deep-squat-stretch','Deep Squat Stretch',ARRAY['glutes'],ARRAY['quads','hamstrings'],'bodyweight','stretch','stretch'),
  ('e-90-90-stretch','90/90 Hip Stretch',ARRAY['glutes'],ARRAY['hamstrings'],'bodyweight','stretch','stretch'),
  ('e-cat-cow','Cat-Cow',ARRAY['back'],ARRAY['core'],'bodyweight','stretch','stretch'),
  ('e-thread-needle','Thread the Needle',ARRAY['back'],ARRAY['shoulders'],'bodyweight','stretch','stretch'),
  ('e-pec-stretch-doorway','Doorway Pec Stretch',ARRAY['chest'],ARRAY['shoulders'],'bodyweight','stretch','stretch'),
  ('e-triceps-stretch','Overhead Triceps Stretch',ARRAY['triceps'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-figure4-stretch','Figure 4 Stretch',ARRAY['glutes'],ARRAY[]::text[],'bodyweight','stretch','stretch'),
  ('e-couch-stretch','Couch Stretch',ARRAY['quads'],ARRAY['glutes'],'bodyweight','stretch','stretch'),
  ('e-foam-roll-calves','Foam Roll — Calves',ARRAY['calves'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-foam-roll-hamstrings','Foam Roll — Hamstrings',ARRAY['hamstrings'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-foam-roll-glutes','Foam Roll — Glutes',ARRAY['glutes'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-foam-roll-lats','Foam Roll — Lats',ARRAY['lats'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-foam-roll-chest','Foam Roll — Chest (Pec)',ARRAY['chest'],ARRAY[]::text[],'other','stretch','stretch'),
  ('e-lacrosse-ball-traps','Lacrosse Ball — Traps',ARRAY['traps'],ARRAY['shoulders'],'other','stretch','stretch'),
  ('e-lacrosse-ball-glutes','Lacrosse Ball — Glutes',ARRAY['glutes'],ARRAY[]::text[],'other','stretch','stretch')

ON CONFLICT (db_id) DO NOTHING;
